# fly.toml app configuration file for Stable Diffusion XL
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

# Fly.io configuration para Stable Diffusion XL con GPU
app = "stable-diffusion-xl"
primary_region = "ord"

[build]

[env]
  PYTHONUNBUFFERED = "1"
  CUDA_VISIBLE_DEVICES = "0"
  TORCH_CUDA_ARCH_LIST = "8.0;8.6;8.9"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

# Configuración para GPU A100 (más rápido)
[[vm]]
  size = "a100-40gb"

# Configuración alternativa sin GPU (más lento)
# [[vm]]
#   size = "performance-8x"

# Configuración para GPU (opcional - más rápido)
# [[vm]]
#   size = "a100-40gb"

# Volumen para cachear el modelo SDXL (50GB para asegurar espacio suficiente)
[mounts]
  source = "sdxl_cache"
  destination = "/root/.cache/huggingface"
